//import 'package:json_model/json_model.dart';
// import 'models/index.dart'; // Generated by json_model tool

void main() {
  // var u = User.fromJson({"name": "Jack", "age": 16, "+1": 20});
  // print(u.loved);
  print('Run `dart run json_model` first to generate model files.');
}
